encoder:
    type: Encoder
    args:
        kernel_size: 16
        out_channels: 256

decoder:
    type: Decoder
    args:
        in_channels: 256
        out_channels: 1
        kernel_size: 16
        stride: 8
        bias: False

trainset:
    type: tr_dataset
    args:
        noise_scp: /public/home/qinxy/jz/data/avse1_data/train/inter_noise.scp
        inter_scp: /public/home/qinxy/jz/data/avse1_data/train/inter.scp
        # s1_scp: /public/home/qinxy/zbang/data/wsj/wav8k/min/list/train/s1.scp
        # s2_scp: /public/home/qinxy/zbang/data/wsj/wav8k/min/list/train/s2.scp
        tar_scp: /public/home/qinxy/jz/data/avse1_data/train/tar.scp
        lip_scp: /public/home/qinxy/jz/data/avse1_data/train/lip.scp
        fs: 16000

trainloader:
    type: TruncateDataLoader
    args:
        trun_range: [48000, 48000]
        step: 1
        shuffle: True
        batch_size: 4
        num_workers: 2
        drop_last: False

testset:
    type: tr_dataset
    args:
        noise_scp: /public/home/qinxy/jz/data/avse1_data/dev/inter_noise.scp
        inter_scp: /public/home/qinxy/jz/data/avse1_data/dev/inter.scp
        # s1_scp: /public/home/qinxy/zbang/data/wsj/wav8k/min/list/train/s1.scp
        # s2_scp: /public/home/qinxy/zbang/data/wsj/wav8k/min/list/train/s2.scp
        tar_scp: /public/home/qinxy/jz/data/avse1_data/dev/tar.scp
        lip_scp: /public/home/qinxy/jz/data/avse1_data/dev/lip.scp
        fs: 16000

testloader:
    type: TruncateDataLoader
    args:
        trun_range: [48000, 48000]
        batch_size: 4
        num_workers: 2
        shuffle: True
        drop_last: False

inferset:
    type: inf_dataset
    args:
        mix_scp: /public/home/qinxy/jz/data/avse3_data/test/dcunet_mix.scp
        # s1_scp: /public/home/qinxy/zbang/data/wsj/wav8k/min/list/train/s1.scp
        # s2_scp: /public/home/qinxy/zbang/data/wsj/wav8k/min/list/train/s2.scp
        lip_scp: /public/home/qinxy/jz/data/avse3_data/test/mouth.scp
        fs: 16000

inferloader:
    type: InfDataLoader
    args:
        trun_range: [64000, 64000]
        batch_size: 1
        num_workers: 2
        shuffle: False
        drop_last: False

optimizer:
    type: Adam
    args:
        lr: 0.001
        weight_decay: 0

# # wsj0-2mix
# tfgridnet_kwargs:
#     n_srcs: 2
#     n_fft: 128
#     stride: 64
#     window: hann
#     n_imics: 1
#     n_layers: 6
#     lstm_hidden_units: 192
#     attn_n_head: 4
#     attn_approx_qk_dim: 512
#     emb_dim: 48
#     emb_ks: 4
#     emb_hs: 1
#     activation: prelu
#     eps: 1.0e-5
#     use_builtin_complex: False
#     ref_channel: -1

# avse challenge old
# tfgridnet_kwargs:
#     n_srcs: 1
#     n_fft: 512
#     stride: 256
#     window: hann
#     n_imics: 1
#     n_layers: 3
#     lstm_hidden_units: 256
#     attn_n_head: 4
#     attn_approx_qk_dim: 256
#     emb_dim: 128
#     emb_ks: 4
#     emb_hs: 2
#     activation: prelu
#     eps: 1.0e-5
#     use_builtin_complex: True
#     ref_channel: -1

# avse challenge original
    
MaskNet:
    n_fft: 512
    hop_length: 320
    win_length: 512
    embd_dim: 512
    feature_dim: 257

MaskNetV2:
    n_fft: 512
    hop_length: 320
    win_length: 512
    embd_dim: 512
    feature_dim: 257
    fc_dim: 16
    emb_ks: 1
    emb_hs: 1
    num_layers: 3
    lstm_hidden_units: 32

RandomRirGenerator_kwargs:
    fs: 16000
    t60_range: [ 0.05, 0.55 ] # rvb:[0.05, 0.7]
    roomdim_range_x: [ 4.0, 10.0 ]
    roomdim_range_y: [ 4.0, 8.0 ]
    roomdim_range_z: [ 2.5, 6.0 ]
    micpos_range_z: [ 0.8, 1.2 ]
    micpos: linear
    # micarray: custom_linear6
    micarray: mono